require("config.options")
require("config.keymaps")
require("config.colorscheme")
require("plugins.packer")
require("config.lsp")
vim.api.nvim_exec([[ autocmd BufWritePre *.go :lua require('go.format').goimport() ]], false)
